name: shotplay_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.4
  provider: ^6.1.5
  flutter_bloc: ^9.1.0
  google_fonts: ^6.3.2
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.10
  flutter_screenutil: ^5.9.3
  uuid: ^4.5.3
  dio: ^5.9.2
  equatable: ^2.0.8
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/impostor/
    - assets/images/
    - .env
